---

  version: "3.6"
  
  services:
    postgres:
      image: postgres:10-alpine
      ports:
        - "127.0.0.1:5432:5432"
      environment:
        POSTGRES_HOST_AUTH_METHOD: "trust"
      volumes:
        - type: volume
          source: postgres_data
          target: /var/lib/postgresql/data
  
    redis:
      image: redis:5-alpine
      ports:
        - "127.0.0.1:6379:6379"
      volumes:
        - type: volume
          source: redis_data
          target: /data
  
  volumes:
    postgres_data:
    redis_data:
